version: "3.8"
# Put URL to http://backend:8099 in todo-list-frontend/proxy.config.json if using this

services:
  backend:
    build:
      context: .
      dockerfile: todo-list-backend/Dockerfile
    ports:
      - "8099:8099"
    volumes:
      - ./todo-list-backend:/app
      - /app/node_modules    # empêche les conflits entre dépendances locales et conteneur
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: .
      dockerfile: todo-list-frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./todo-list-frontend:/app